

# Form implementation generated from reading ui file '.\sagrave.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gui(object):
    def setupUi(self, gui):
        gui.setObjectName("gui")
        gui.setWindowModality(QtCore.Qt.ApplicationModal)
        gui.resize(871, 684)
        self.centralwidget = QtWidgets.QWidget(gui)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 871, 661))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabletTracking(True)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.p_cartes = QtWidgets.QWidget()
        self.p_cartes.setObjectName("p_cartes")
        self.tableWidget = QtWidgets.QTableWidget(self.p_cartes)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 861, 651))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tabWidget.addTab(self.p_cartes, "")
        self.p_transactions = QtWidgets.QWidget()
        self.p_transactions.setObjectName("p_transactions")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.p_transactions)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 861, 651))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_2.addWidget(self.dateEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.horizontalLayout_2.addWidget(self.dateEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(858, 2, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.columnView = QtWidgets.QColumnView(self.verticalLayoutWidget)
        self.columnView.setObjectName("columnView")
        self.verticalLayout.addWidget(self.columnView)
        self.tabWidget.addTab(self.p_transactions, "")
        self.p_decompte = QtWidgets.QWidget()
        self.p_decompte.setObjectName("p_decompte")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.p_decompte)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 860, 631))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.dateEdit_7 = QtWidgets.QDateEdit(self.verticalLayoutWidget_4)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.horizontalLayout_5.addWidget(self.dateEdit_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.dateEdit_8 = QtWidgets.QDateEdit(self.verticalLayoutWidget_4)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.horizontalLayout_5.addWidget(self.dateEdit_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(858, 2, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.treeWidget = QtWidgets.QTreeWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setColumnCount(2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.headerItem().setText(1, "2")
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.tabWidget.addTab(self.p_decompte, "")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        gui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        gui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gui)
        self.statusbar.setObjectName("statusbar")
        gui.setStatusBar(self.statusbar)
        self.actionQuitter = QtWidgets.QAction(gui)
        self.actionQuitter.setObjectName("actionQuitter")
        self.actionOuvrir = QtWidgets.QAction(gui)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionSetting = QtWidgets.QAction(gui)
        self.actionSetting.setObjectName("actionSetting")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addSeparator()
        self.menuFichier.addAction(self.actionQuitter)
        self.menuHelp.addAction(self.actionSetting)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(gui)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(gui)

    def retranslateUi(self, gui):
        _translate = QtCore.QCoreApplication.translate
        gui.setWindowTitle(_translate("gui", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.p_cartes), _translate("gui", "Cartes"))
        self.label.setText(_translate("gui", "Date d├®but"))
        self.label_2.setText(_translate("gui", "Date Fin"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.p_transactions), _translate("gui", "Transactions"))
        self.label_7.setText(_translate("gui", "Date d├®but"))
        self.label_8.setText(_translate("gui", "Date Fin"))
        self.treeWidget.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.p_decompte), _translate("gui", "Decompte"))
        self.menuFichier.setTitle(_translate("gui", "Fichier"))
        self.menuHelp.setTitle(_translate("gui", "Help"))
        self.actionQuitter.setText(_translate("gui", "Quitter"))
        self.actionOuvrir.setText(_translate("gui", "Ouvrir"))
        self.actionSetting.setText(_translate("gui", "Setting"))
